# Shell variables
# Generated by 'wal'
wallpaper='/home/ninewb/wallpaper.jpg'

# Special
background='#341f68'
foreground='#dfe4ed'
cursor='#dfe4ed'

# Colors
color0='#341f68'
color1='#4161B5'
color2='#6269BD'
color3='#6679C1'
color4='#2B85BA'
color5='#658DC6'
color6='#A1B3DA'
color7='#dfe4ed'
color8='#9c9fa5'
color9='#4161B5'
color10='#6269BD'
color11='#6679C1'
color12='#2B85BA'
color13='#658DC6'
color14='#A1B3DA'
color15='#dfe4ed'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
